apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend
spec:
  replicas: 2 # Number of Pods to run
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: ecommerce-frontend-web-app:latest # Replace with your image
        imagePullPolicy: IfNotPresent # Always pull the latest image
        ports:
        - containerPort: 4200
        command: ["ng", "serve", "--host", "0.0.0.0"] # Ensure it binds to all interfaces
