apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
  - protocol: TCP
    port: 4200 # The port the Service exposes
    targetPort: 4200 # The port the container listens on
    nodePort: 30000 # Optional: Expose on a specific port (30000-32767)
  type: NodePort
